loy/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('infopages.urls', namespace="infopage")),
    url(r'^member/', include('members.urls', namespace="member")),
    url(r'^admin/', include(admin.site.urls)),
]

members/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^forgot/$', views.forgotpassword, name='forgotpassword'),
    url(r'^(?P<username>\w+)/$', views.profileview, name='profile'),
    url(r'^(?P<username>\w+)/private/$', views.privateprofile, name='private'),
    url(r'^(?P<username>\w+)/(?P<emailid>\w+)/$', views.emailconfirm, name='emailconfirm'),
]

members/models.py
from django.db import models
from datetime import date
from django.contrib.auth.hashers import make_password

class Member(models.Model):
    GENDER = (
    ('MA', 'Male'),
    ('FM', 'Female'),
    ('NA', 'None'),
        )
    
    user_name = models.CharField(max_length=30, unique=True)
    user_name_mask = models.CharField('User Name', max_length=30)
    password = models.CharField(max_length=255)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=75)
    gender = models.CharField(max_length=2,
                              choices=GENDER,
                              default='NA')
    dob = models.DateField('Date of Birth')
    email = models.EmailField(unique=True)
    join_date = models.DateTimeField('Joined Date', auto_now_add=True)
    last_login = models.DateTimeField('Last Logged in', auto_now_add=True)
    active_member= models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    founder_member = models.BooleanField(default=False)

    email_confirm = models.BooleanField(default=False)
    confirm_id = models.CharField(max_length=128, null=True)
    memorable_word = models.CharField(max_length=20)
    profile_private = models.BooleanField('Private profile', default=False)
    def __str__(self):
        return self.user_name_mask
    
    def returnage(self):
        today = date.today()
        return today.year - self.dob.year - ((today.month, today.day) < (self.dob.month, self.dob.day))

    def reset_password(self, new_password):
        self.password = make_password(new_password)
        self.save()

    returnage.short_description = "Age"

members/forms.py
from django import forms
from django.contrib.auth.hashers import check_password
import re
from .models import Member

class LoginForm(forms.Form):
    user_name = forms.CharField(label='User Name', max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control'}))
    password = forms.CharField(label='Password', max_length=255, widget=forms.PasswordInput(attrs={
        'class': 'form-control'}))
    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        try:
            user_name = self.cleaned_data['user_name']
            password = self.cleaned_data['password']
        except:
            return
        else:
            if not self.username_check(user_name, password):
                self.add_error('user_name', 'Invalid User Name/Password or Account not active')
            
    def username_check(self, username, password):
        try:
            m = Member.objects.get(user_name=str(username).lower())
        except:
            return False
        else:
            if not check_password(password, m.password) or not m.active_member:
                return False
            return True

class RegisterForm(forms.Form):
    user_name = forms.CharField(label="User Name", max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'User Name'}))
    first_name = forms.CharField(label="First Name", max_length=50, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'First Name'}))
    last_name = forms.CharField(label="Last Name", max_length=75, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Last Name'}))
    dob = forms.DateField(label="Date of Birth", widget=forms.DateInput(attrs={
        'class': 'form-control datepicker', 'placeholder': 'Date of Birth'}), input_formats=
                          ['%d %B, %Y', '%d %b, %Y', '%d %b, %y', '%d/%m/%Y', '%d/%m/%y'])
    gender = forms.ChoiceField(label="Gender", choices=Member.GENDER, widget=forms.Select(attrs={
        'class': 'form-control'}))
    email = forms.EmailField(label="Email", max_length=254, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Email Address'}))
    memorable_word = forms.CharField(label="Memborable Word", max_length=20, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Used for password resets'}))
    password = forms.CharField(label='Password', max_length=255, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Password'}))
    password_confirm = forms.CharField(label='Confirm Password', max_length=255, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Confirm Password'}))

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        user_name = self.cleaned_data.get('user_name', '')
        email = self.cleaned_data.get('email', '')
        password = self.cleaned_data.get('password', None)
        pass_confirm = self.cleaned_data.get('password_confirm', None)
        if not re.match("^[a-zA-Z0-9_]*$",user_name) or len(user_name) < 3:
            self.add_error('user_name', 'User Name contains an invalid charater or it is too short')
        if not self.unique_check(user_name):
            self.add_error('user_name', 'User Name is already being used')
        if not self.unique_check(email, True):
            self.add_error('email', 'Email address is already being used')
        if not passwordCheck(password, pass_confirm):
            self.add_error('password', "Password must be longer than 8 charaters")
            self.add_error('password_confirm', "Passwords need to match")

    def unique_check(self, value, email=False):
        try:
            if email:
                m = Member.objects.get(email=value)
            else:
                m = Member.objects.get(user_name=str(value).lower())
        except:
            return True
        else:
            return False

class ForgotForm(forms.Form):
    user_name = forms.CharField(label="User Name", max_length=30, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'User Name'}))
    email = forms.EmailField(label="Email", max_length=254, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Email Address'}))
    memorable_word = forms.CharField(label="Memborable Word", max_length=20, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Enter memorable word'}))
    new_password = forms.CharField(label='New Password', max_length=255, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Password'}))
    password_confirm = forms.CharField(label='Confirm Password', max_length=255, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Confirm Password'}))

    def clean(self):
        cleaned_data = super(ForgotForm, self).clean()
        username = self.cleaned_data.get('user_name', None)
        email = self.cleaned_data.get('email', None)
        mem_word = self.cleaned_data.get('memorable_word', None)
        password = self.cleaned_data.get('new_password', None)
        pass_confirm = self.cleaned_data.get('password_confirm', None)
        if username and email:
            try:
                m = Member.objects.get(user_name=username.lower(), email=email)
            except:
                self.add_error('user_name', "No match found")
            else:
                if m.memorable_word != mem_word:
                    self.add_error('memorable_word', "Doesn't match")
        if not passwordCheck(password, pass_confirm):
            self.add_error('new_password', "Password must be longer than 8 charaters")
            self.add_error('password_confirm', "Passwords need to match")

class SearchForm(forms.Form):
    search_field = forms.CharField(label="", max_length=50, required=False, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Search'}))

def passwordCheck(password, confirm_password):
    if not password or not confirm_password:
        return False
    if password and confirm_password and (password != confirm_password):
        return False
    if len(password) < 8:
        return False
    return True
        
    

members/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.hashers import make_password, check_password
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from loy.access import Access
from .email import EmailUser
from .models import Member
from datetime import datetime
from .forms import LoginForm, RegisterForm, ForgotForm, SearchForm
import logging

logger = logging.getLogger(__name__)

def index(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        member_list = Member.objects.filter(active_member=True)
        if form.is_valid():
            s_value = form.cleaned_data['search_field']
            member_list = member_list.filter(user_name__contains=s_value)
    else:
        form = SearchForm()
        member_list = Member.objects.filter(active_member=True)
    member_list = member_list.order_by('-join_date', 'last_login')
    paginator = Paginator(member_list,20)
    page = request.GET.get('page')
    try:
        members = paginator.page(page)
    except PageNotAnInteger:
        members = paginator.page(1)
    except EmptyPage:
        members = paginator.page(paginator.num_pages)
    return render(request, 'members/index.html', {'members': members, 'form': form})

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = form.cleaned_data['user_name']
            m = Member.objects.get(user_name=user.lower())
            m.last_login = datetime.now()
            try:
                m.save()
                request.session['member_id'] = m.id
            except Exception, e:
                return render(request,'members/login_error.html', {'form': form, 'error_message': e})
            else:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))
    else:
        form = LoginForm()
    return render(request,'members/login_error.html', {'form': form})

def logout(request):
    del request.session['member_id']
    return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))

def forgotpassword(request):
    if request.method == 'POST':
        form = ForgotForm(request.POST)
        if form.is_valid():
            try:
                m = Member.objects.get(user_name=form.cleaned_data['user_name'].lower())
                m.reset_password(form.cleaned_data['new_password'])
            except Exception, e:
                return render(request, 'members/register.html', {
                    'form': form,
                    'error_message': e})
            else:
                return redirect('/')
    else:
        form = ForgotForm()
    return render(request, 'members/forgot_password.html', {'form': form})

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            try:
                e = EmailUser(form.cleaned_data['email'], form.cleaned_data['user_name'])
                m = Member(user_name=form.cleaned_data['user_name'].lower(),
                           user_name_mask=form.cleaned_data['user_name'],
                           password=make_password(form.cleaned_data['password']),
                           first_name=form.cleaned_data['first_name'],
                           last_name=form.cleaned_data['last_name'],
                           gender=form.cleaned_data['gender'],
                           dob=form.cleaned_data['dob'],
                           email=form.cleaned_data['email'],
                           memorable_word=form.cleaned_data['memorable_word'],
                           confirm_id=e.send_email())
                m.save()
            except Exception, e:
                return render(request, 'members/register.html', {
                    'form': form,
                    'error_message': e})
            else:
                #redirect to success page to be set up
                return redirect('/')
    else:
        form = RegisterForm()
    return render(request, 'members/register.html', {'form': form})

def emailconfirm(request, username, emailid):
    m = get_object_or_404(Member, user_name=username)
    print m.confirm_id
    if not m.confirm_id or (m.confirm_id != emailid):
        raise Http404()
    m.email_confirm = True
    m.active_member = True
    m.confirm_id = None
    m.save()
    return render(request, 'members/accountactivated.html', {'username': m.user_name_mask})

def profileview(request, username):
    m = get_object_or_404(Member, user_name=username)
    return render(request, 'members/profileview.html', {'member': m})

def privateprofile(request, username):
    m = get_object_or_404(Member, user_name=username)
    try:
        r_id = request.session['member_id']
    except KeyError:
        raise Http404()
    if r_id != m.id:
        raise Http404()
    if m.profile_private:
        m.profile_private = False
    else:
        m.profile_private = True
    m.save()
    return HttpResponseRedirect('/member/%s' % username)

members/templates/members/accountactivated.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	<div class="page-header">
		<h1>Welcome to League of Yorkshire</h1>
	</div>
	<div class="container">
		<p>Your account is now active {{ username }}</p>
		<p>You now have full access to the site</p>
	</div>
{% endblock %}

members/templates/members/emailactivate.html
<div class="msg">
	<h2>Hello <strong>{{ username }}</strong></h2><br/>
	<p>Please follow this link to activate your account, <a href="{{ account_link }}">{{ account_link }}</a></p>
</div>

members/templates/members/forgot_password.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	<div class="page-header">
		<h1>Forgotten Password Form</h1>
	</div>
	<div class="container">
		<form method="post" action="{% url 'member:forgotpassword' %}">
			{% csrf_token %}
			{{ form }}
			{% if error_message %}<p class="errorlist">{{ error_message }}</p>{% endif %}
			<button type="submit" class="btn btn-default">Submit</button>
		</form>
	</div>
{% endblock %}

members/templates/members/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	<div class="page-header">
		<h1>League of Yorkshire Members</h1>
	</div>
	<div class="container">
		<form class="form-inline" method="post" action="{% url 'member:index' %}">
			{% csrf_token %}
			<div class="form-group">
				{{ form }}
				<button type="submit" class="btn btn-default">Search</button>
			</div>
		</form>
		<table class="table">
			<thead>
				<th>User Name</th>
				<th>Joined Date</th>
				<th>Last Logged in</th>
				<th>Admin</th>
			</thead>
			<tbody>
			{% for member in members %}
				<tr>
					<td><a href="{{ member.user_name }}/">{{ member.user_name_mask }}</a></td>
					<td>{{ member.join_date|date:"d F Y" }}</td>
					<td>{{ member.last_login|timesince }} ago</td>
					<td>{% if member.admin %}<span class="glyphicon glyphicon-ok"></span>{% endif %}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
		<nav>
			<ul class="pager">
				{% if members.has_previous %}
				<li class="previous"><a href="?page={{ members.previous_page_number }}"><span aria-hidden="true">&larr;</span> Back</a></li>
				{% endif %}
				<span class="current">
					Page {{ members.number }} of {{ members.paginator.num_pages }}.
				</span>
				{% if members.has_next %}
				<li class="next"><a href="?page={{ members.next_page_number }}"><span aria-hidden="true">&rarr;</span> Next</a></li>
				{% endif %}
			</ul>
		</nav>
	</div>
{% endblock %}

members/templates/members/login_error.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	<form method="post" action="{% url 'member:login' %}">
		{% csrf_token %}
		{{ form }}
		{% if error_message %}<p class="errorlist">{{ error_message }}</p>{% endif %}
		<button type="submit" class="btn btn-default">Login</button>
		<a href="#" class="btn btn-default">Forgot Password</a>
	</form>
{% endblock %}

members/templates/members/profileview.html
{% extends "base.html" %}
{% load staticfiles %}
{% load members_extras %}

{% block content %}
	<div class="page-header">
		<h1>{{ member.user_name_mask }}'s Profile</h1>
	</div>
	{% if request.session.member_id != member.id and member.profile_private %}
	<div>
		<h3>This profile is set to private</h3>
	</div>
	{% else %}
	{% if request.session.member_id == member.id %}
	<div>
		<a href="#">Edit Profile</a><br/>
		<a href="private/">Make Profile {% if member.profile_private %}Public{% else %}Private{% endif %}</a>
	</div>
	{% endif %}
	<div class="member-info">
		<div class="info-box">
			<div class="profile-header">
				<h3>Personal Information</h3>
			</div>
			<div class="member-profile-pic">
				<img src="{% static 'images/ppImage.png' %}">
			</div>
			<ul>
				{% if member.admin %}<li>Site Admin</li>{% endif %}
				{% if member.founder_member %}<li>Site Founder</li>{% endif %}
				<li>IRL Name: {{ member.first_name}} {{ member.last_name }}</li>
				<li>Age: {{ member.returnage }}</li>
				<li>Joined: {{ member.join_date|date:"d F Y" }}</li>
				<li>Gender: {{ member.gender|return_gender }}</li>
				<li>Last logged in: {{ member.last_login|timesince }} ago</li>
			</ul>
		</div>
		<div class="info-box additional">
		</div>
	</div>
	{% endif %}
{% endblock %}

members/templates/members/register.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	<div class="page-header">
		<h1>Register Form</h1>
	</div>
	<div class="container">
		<form method="post" action="{% url 'member:register' %}">
			{% csrf_token %}
			{{ form }}
			{% if error_message %}<p class="errorlist">{{ error_message }}</p>{% endif %}
			<button type="submit" class="btn btn-default">Submit</button>
		</form>
	</div>
{% endblock %}